[workspace]
authors = ["jgunstone <j.gunstone@maxfordham.com>"]
channels = ["conda-forge"]
name = "uknzcb-eui-benchmarks"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
frictionless = ">=5.18.1,<6"
pandas = ">=2.3.3,<3"
stringcase = ">=1.2.0,<2"
openpyxl = ">=3.1.5,<4"

[tasks]
get-eui = { cmd = "python get_eui.py", cwd = "scripts" }
create-datapackage = { cmd = "python create_datapackage.py", cwd = "scripts" }
